### ISSUE TITLE
PDF: Some text in tables overlaps

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#1]
PDF: Some text in tables overlaps (see EBH-tables-issue.png).
![EBH-tables-issue](https://user-images.githubusercontent.com/43754593/71518107-7aa24a00-28b1-11ea-83f4-c45d0562367a.png)

**Comment by reinaldoarrosi** [comment]
According to Pandoc's documentation (https://pandoc.org/MANUAL.html#tables)

> If a pipe table contains a row whose printable content is wider than the column width (see --columns), then the table will take up the full text width and the cell contents will wrap, with the relative cell widths determined by the number of dashes in the line separating the table header from the table body. (For example ---|- would make the first column 3/4 and the second column 1/4 of the full text width.)

So I just had to resize some table columns by adding more dashes to them. I've also changed md2all.bat to set --columns, since one of the tables was not word-wrapping.

**Comment by ZSvedic** [comment]
@reinaldoarrosi Unfortunately, after font is back to arev, some text in tables still overlaps. For example, in EBH-print.pdf, page 28:
![image](https://user-images.githubusercontent.com/43754593/72666443-a1682200-3a12-11ea-8b40-41ca88983c9d.png)

**Comment by ZSvedic** [comment]
@reinaldoarrosi Partially connected to above: can we make font size in tables a bit smaller for PDFs?
