### ISSUE TITLE
Font switches after first two pages

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#13]
In front-matter.md, 5th line says to use specific sans-serif font ([arev](https://tug.org/FontCatalogue/arev/)):
"fontfamily: arev"

However, in the current build (2019-1-17), PDF reverts to default Times New Roman after first two pages:
![image](https://user-images.githubusercontent.com/43754593/72625571-4b7b7780-3949-11ea-8fb3-5d7f35b04f28.png)

**Comment by reinaldoarrosi** [comment]
This was caused by the changes I've made to move copyright pages before TOC.

To fix this, I moved the font family configuration to the .sty files
