### ISSUE TITLE
Images in PDF should also have captions

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#14]
Figures in HTML and EPUB have captions below. But both PDFs don't display captions below, see the image:
![image](https://user-images.githubusercontent.com/43754593/72742362-d78bda00-3ba9-11ea-9481-17dedbdb81d3.png)

**Comment by reinaldoarrosi** [comment]
Pandoc already adds captions to images by default (even in PDF). We "lost" captions when we added the LUA script to center all images. 

I've fixed the LUA script to preserve captions.
