### ISSUE TITLE
Make PDF titles prettier

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#15]
A. Old titles were larger. 
B. Old "CHAPTER X" was in a separate line.
See image below:
![image](https://user-images.githubusercontent.com/43754593/72744458-eb393f80-3bad-11ea-9aca-ed32cc631126.png)

If B is complicated, skip it.

**Comment by reinaldoarrosi** [comment]
Since item B requires custom LUA scripts and even then breaks the table-of-contents, I just increased the size of titles and sub-titles.
