### ISSUE TITLE
PDF for print has few table issues 

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#16]
A. Unnecessary table continuation on page 28, see the screenshot:
![image](https://user-images.githubusercontent.com/43754593/72745516-38b6ac00-3bb0-11ea-90ab-084ba7ff0db3.png)

B. Unnecessary table empty space on page 31, see the screenshot:
![image](https://user-images.githubusercontent.com/43754593/72745763-ca261e00-3bb0-11ea-8c42-d360bf158758.png)

C. Table overflowing is issue in both EBH-print.pdf (page 37) and EBH-standalone.pdf (page 35), see the screenshot:
![image](https://user-images.githubusercontent.com/43754593/72746120-9e576800-3bb1-11ea-8340-54c5e95dbd3e.png)

D. Header too high issues in EBH-print.pdf (pages: 78, 85, 87, 88, 89) and EBH-standalone.pdf (pages: 74, 80, 83, 84), see the screenshot:
![image](https://user-images.githubusercontent.com/43754593/72748941-efb72580-3bb8-11ea-8ff9-2915329731da.png)

**Comment by reinaldoarrosi** [comment]
Regarding item B, apparently page-breaks in a table row are not possible in LaTeX (https://tex.stackexchange.com/questions/78578/longtable-page-breaks-within-row-possible)

In the provided example the contents of the "Description" column would not fit the current page, so the whole table row is moved to the next page.
