### ISSUE TITLE
Amazon Kindle style issues

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#20]
After uploading EPUB to Amazon KDP (Kindle Direct Publishing), converting to MOBI and using Kindle Preview, I have noticed a few more minor style issues:

- [x] Copyright line on Title page is unnecessary and wrongly positioned. I suggest removing it from that page:
![EPUB-issue-title-page](https://user-images.githubusercontent.com/43754593/73607293-76560480-45b4-11ea-8ceb-e8b9556fb5b0.png)

- [x] There is a big unnecessary space above TOC:
![EPUB-issue-TOC](https://user-images.githubusercontent.com/43754593/73607297-91c10f80-45b4-11ea-8be5-81e2bce967a7.png)

- [x] After TOC, there is another title page, this time just with title? I suggest removing that page:
![EPUB-issue-page-after-TOC](https://user-images.githubusercontent.com/43754593/73607308-bcab6380-45b4-11ea-8666-6e0d4f011399.png)

- [x] References are messed up, there is a big space between ":" and link. I think it is caused by Kindle default text being justified not left aligned:
![EPUB-issue-references](https://user-images.githubusercontent.com/43754593/73607328-0136ff00-45b5-11ea-9007-0ecf0105cba4.png)

But, not all is bad :) When KDP converted EPUB to MOBI, it had reduced EPUB 5.47 MB to MOBI 2.36 MB:
![EPUB-MOBI-conversion](https://user-images.githubusercontent.com/43754593/73607347-32afca80-45b5-11ea-8f75-a67f81fa4f07.png)

**Comment by ZSvedic** [comment]
@reinaldoarrosi  What is the status of this?

**Comment by reinaldoarrosi** [comment]
I've fixed these issues. 
I checked it using Kindle Previewer and it looks OK.
