### ISSUE TITLE
Amazon print-on demand issues

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#21]
After uploading EPUB to Amazon KDP (Kindle Direct Publishing) and watching a page-by-page preview  I have noticed one more style issue.

The issue is that tables with 5 columns just don't work in small format:
![PDF-print-table-issue](https://user-images.githubusercontent.com/43754593/73607510-1c0a7300-45b7-11ea-8542-a00a0b67155a.png)

As you can see, words are broken into two rows like "candi-date", "inter-view" etc.

Solution is to either reduce font size for this table, or restructure table to have less columns. For example, we can merge _Company effort_ and _Candidate effort_ columns, and _Step_ and _Validity_ columns?

**Comment by ZSvedic** [comment]
@reinaldoarrosi  What is the status of this?

**Comment by reinaldoarrosi** [comment]
I tried merging Company effort and Candidate effort into a single column but it still doesn't look good.

![image](https://user-images.githubusercontent.com/5149327/81511836-76237e80-92f2-11ea-9b15-51650bf1e41a.png)

I'll try to reduce the font-size of the table, but I did some research and it seems that to do this I'll need to write a custom LUA script for Pandoc

**Comment by ZSvedic** [comment]
@reinaldoarrosi OK. Except reducing font size with Lua, another option is ditching table altogether and using bullets with indentation. For example:
- Step: On-site assessment and knowledge test
  - Company effort: ...
  - Candidate effort: ...
  - Reward: ...
  - Validity: ...

Let me know what is better.

**Comment by reinaldoarrosi** [comment]
I've added a LUA filter to reduce the font-size of tables on PDF files. 

I've checked all existing tables and I think they all look nicer with a smaller font-size, so this filter is reducing the font-size of all tables.

Let me know what you think 😀
