### ISSUE TITLE
Amazon KDP - issues with cover in paperback version

### ISSUE THREAD

**Issue by reinaldoarrosi** [ZSvedic/EBH-book#22]
The exact error reported by Amazon KDP is:

> Cover
Reduce the size of your spine text in your cover file. Spine text needs at least 0.0625" (1.6 mm) space on either side so that it doesn't wrap onto the front or back cover

**Comment by reinaldoarrosi** [comment]
@ZSvedic We lost 21 pages when we reduced the size of tables (from 126 to 105). I can add empty pages to the end of the book as you suggested, but will it not look weird to have 21 blank pages at the end?

**Comment by ZSvedic** [comment]
@reinaldoarrosi You are right, adding 21 blank pages is too much. I have asked Damir from GemBox to try to edit [the cover file](https://github.com/ZSvedic/EBH-book/blob/master/Amazon/EBH-cover.pdf), as he has the license for Adobe Acrobat.

**Comment by ZSvedic** [comment]
Amazon KDP approved Damir's out2 file with reduced spine text. I have uploaded that new cover to https://github.com/ZSvedic/EBH-book/tree/master/Amazon
