### ISSUE TITLE
PDF: Images should be centered

### ISSUE THREAD

**Issue by ZSvedic** [ZSvedic/EBH-book#4]
Currently all images in PDF are left-aligned. See the About author page for example.

**Comment by ZSvedic** [comment]
https://stackoverflow.com/questions/24677642/centering-image-and-text-in-r-markdown-for-a-pdf-report

**Comment by reinaldoarrosi** [comment]
I've created a LUA script (pdf-center-images.lua) that centers all images except those that have the "not-centered" class. 

The by-nd.png image in front-matter.md is an example of how to use the "not-centered" class
```
![](../images/by-nd.png){.not-centered width=25%}
```
